### ISSUE TITLE
Distribute this package via pypi and Debian/Ubuntu

### ISSUE THREAD

**Issue by PanderMusubi** [python-acoustics/python-acoustics#110]
Please distribute this package via pypi and Debian/Ubuntu. Contact me for packaging requiest for the latter.

**Comment by felipeacsi** [comment]
Thanks for the offer.

Since we haven't released the package, this will require some effort to clean and do some old tasks. I think it is a good idea to plan a first release. I can do some work on old issues and prepare the release at least through PyPI. What do you think @FRidh?

**Comment by FRidh** [comment]
Hi,

Thank you for your interest and your offer. It would definitely be possible to package it for pypi and/or Debian/Ubuntu. I actually released a test version once on pypi: https://pypi.python.org/pypi/acoustics/0.0

I think with the current state of the repository it won't be hard to create and release a package. However, as Felipe noted, it requires quite a lot of cleaning. In the past year or so I've basically been dumping in the things I use for my research and breaking other things as well.

The latter can be a big issue when dealing with releases; nobody likes it when their code stops working because some dependency broke their api. Could you tell me which parts of the package you are interested in and (would) use?

**Comment by PanderMusubi** [comment]
Iterating over all octaves and 1/3 octaves in terms of centre, lower and upper frequencies.

**Comment by FRidh** [comment]
I've released version 0.1, and the following should work `pip install acoustics` although I haven't tested it.

**Comment by PanderMusubi** [comment]
`# apt-get install cython3

    # pip3 install acoustics
    Collecting acoustics
      Using cached acoustics-0.1.0.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-ud6_nho2/acoustics/setup.py", line 56, in <module>
            ext_modules=cythonize('acoustics/*.pyx'),
          File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 758, in cythonize
            aliases=aliases)
          File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 651, in create_extension_list
            for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
          File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 103, in nonempty
            raise ValueError(error_msg)
        ValueError: 'acoustics/*.pyx' doesn't match any files
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ud6_nho2/acoustics/
    You are using pip version 8.1.1, however version 8.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by FRidh** [comment]
could you try again?

**Comment by FRidh** [comment]
(I can't be entirely sure testing this in virtualenv due to how my OS works)

**Comment by FRidh** [comment]
0.1.2 is working on Debian.
