### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by PanderMusubi** [python-acoustics/python-acoustics#111]
Please support Python 3

PS Is Cython really needed in setup.py fo this package?

**Comment by felipeacsi** [comment]
Hello Pander.

Python 3 is currently supported. I work daily with Python 3 since the beginning of this package without problems. Did you have a particular problem? Any information about your system or configuration could be helpful.

Cython won't be needed for releases (we plan to distribute the c files) but it is (and it will be) needed for the development version.

**Comment by FRidh** [comment]
Python 3.4 is fully supported. It's what I use daily.

**Comment by PanderMusubi** [comment]
Ah, building it resulted in a lot of errors. Probably because I was building it myself. So if it installs via pip3 or easy_install3 I want to give it another try.
